// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AchievementsJS
{
        public const string achievement_100_correct_answer = "CgkIwbXkl6ceEAIQFg"; // <GPGSID>
        public const string achievement_exchange_it = "CgkIwbXkl6ceEAIQBA"; // <GPGSID>
        public const string achievement_all_right = "CgkIwbXkl6ceEAIQEg"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIwbXkl6ceEAIQFA"; // <GPGSID>
        public const string achievement_real_collector = "CgkIwbXkl6ceEAIQCg"; // <GPGSID>
        public const string achievement_200_correct_answer = "CgkIwbXkl6ceEAIQFw"; // <GPGSID>
        public const string achievement_bronze_collector = "CgkIwbXkl6ceEAIQCA"; // <GPGSID>
        public const string achievement_first_tile = "CgkIwbXkl6ceEAIQAg"; // <GPGSID>
        public const string achievement_background_expert = "CgkIwbXkl6ceEAIQDQ"; // <GPGSID>
        public const string achievement_first_correct_answer = "CgkIwbXkl6ceEAIQBw"; // <GPGSID>
        public const string achievement_amateur_player = "CgkIwbXkl6ceEAIQDw"; // <GPGSID>
        public const string achievement_first_background = "CgkIwbXkl6ceEAIQAw"; // <GPGSID>
        public const string achievement_character_expert = "CgkIwbXkl6ceEAIQCw"; // <GPGSID>
        public const string achievement_newbie_player = "CgkIwbXkl6ceEAIQDg"; // <GPGSID>
        public const string leaderboard_correct_answer = "CgkIwbXkl6ceEAIQFQ"; // <GPGSID>
        public const string achievement_tile_expert = "CgkIwbXkl6ceEAIQDA"; // <GPGSID>
        public const string achievement_real_player = "CgkIwbXkl6ceEAIQEQ"; // <GPGSID>
        public const string achievement_gold_collector = "CgkIwbXkl6ceEAIQCQ"; // <GPGSID>
        public const string achievement_thanks_ = "CgkIwbXkl6ceEAIQBg"; // <GPGSID>
        public const string achievement_first_character = "CgkIwbXkl6ceEAIQAQ"; // <GPGSID>
        public const string achievement_first_death_ = "CgkIwbXkl6ceEAIQAA"; // <GPGSID>
        public const string achievement_50_correct_answer = "CgkIwbXkl6ceEAIQEw"; // <GPGSID>
        public const string achievement_500_correct_answer = "CgkIwbXkl6ceEAIQGA"; // <GPGSID>
        public const string achievement_good_player = "CgkIwbXkl6ceEAIQEA"; // <GPGSID>

}

